<?php

########################################################################
# Extension Manager/Repository config file for ext: "bgm_theme_bgm"
#
# Auto generated by Extension Builder 2012-04-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'bgm-Theme for MyPage',
	'description' => 'This is the theme for MyPage',
	'category' => 'Themes',
	'author' => 'bgm GmbH & Co. KG',
	'author_email' => 'typo3@bgm-gmbh.de',
	'author_company' => 'bgm GmbH & Co. KG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(

		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>