menu.footernavigationSysfolder = 22
menu.root = 15
sitegeneral.logoAltTtileText = bgm communications
sitegeneral.telephone = +49 (8028) 904 937
sitegeneral.contactName = bgm business group munich GmbH & Co. KG
sitegeneral.contactStreet = Seebergweg 10
sitegeneral.contactCity = 83730 Fischbachau
sitegeneral.contactFax = +49 (8028) 904 972
sitegeneral.copyrightText = bgm business group munich GmbH & Co. KG
sitegeneral.browserTitleSuffix = bgm business group munich
sitegeneral.email = communications@bgm-gmbh.de
sitegeneral.footerStaticContentLeftUid = 93
sitegeneral.footerStaticContentCenterUid = 92
menu.pathToLogo = typo3conf/ext/bgm_theme_bgm/Resources/Public/Images/bgm_logo_communications.png