# A sample Gemfile
source "https://rubygems.org"

ruby '1.9.3'
gem 'sass','3.3.14'
gem 'compass','<=1.0.1'
gem 'singularitygs','<1.5.0'
gem 'breakpoint','<2.6.0'


# Aliases

# alias bcw='bundle exec compass watch'
# alias bcc='bundle exec compass compile'
# alias bi='bundle install'
# alias bu='bundle update'
